export const CREATE_POST = 'POST/CREATE_POST'
export const FETCH_POSTS = 'POST/FETCH_POSTS'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'
export const REQUEST_POST = 'APP/REQUEST_POST'

export const IS_AUTHORIZED = 'IS_AUTHORIZED'
export const IS_FETCHING = 'IS_FETCHING'
export const IS_NOT_AUTHORIZED = 'IS_NOT_AUTHORIZED'
export const IS_NOT_FETCHING = 'IS_NOT_FETCHING'
export const USER_DATA = 'USER_DATA'

export const SHOW_TEXT = 'SHOW_TEXT'

